#
# ==== General info ====
#
# * If a field have default value then the definition may be skipped.
#
# * You can add your own recipes in this file but don't forget to
# add they into 'enabled-recipes' list
#
# * After editing of this file you need to check server logs to be
# sure that no errors was appeared.
#

#
# Show debug info. Possible values: true | false (default = false)
#
# This option can affect the performance.
#
debug: false


# List of keys of enabled recipes
# <recipe-key1>
# ...
# <recipe-keyN>
enabled-recipes:
  - PigSpawner

  - BlazeSpawnEgg
  - CreeperSpawnEgg
  - DrownedSpawnEgg
  - EndermanSpawnEgg
  - GhastSpawnEgg
  - MagmaCubeSpawnEgg
  - PandaSpawnEgg
  - PigSpawnEgg
  - RavagerSpawnEgg
  - ShulkerSpawnEgg
  - SkeletonSpawnEgg
  - SlimeSpawnEgg
  - SpiderSpawnEgg
  - WitherSkeletonSpawnEgg
  - ZombieSpawnEgg

  - Sponge

#
# ==== Recipes definition ====
# Example:
#
# <recipe-key>:
#   name: <String>
#   description: (default = empty)
#     - <String1>
#     ...
#     - <StringN>
#   recipe: (see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html)
#     - <BlockId11> <BlockId12> <BlockId13>
#     - <BlockId21> <BlockId22> <BlockId23>
#     - <BlockId31> <BlockId32> <BlockId33>
#   item: ### target item in recipe result
#   amount: <1..64> ### target amount of items in recipe result (default = 1)
#

PigSpawner:
  name: "Pig Spawner"
  description:
    - "The pig can be changed"
    - "by using a mob spawn egg"
    - "on the block."
  recipe:
    - IRON_BLOCK PORKCHOP IRON_BLOCK
    - PORKCHOP CLOCK PORKCHOP
    - IRON_BLOCK PORKCHOP IRON_BLOCK
  material: SPAWNER

BlazeSpawnEgg:
  name: "Blaze Spawn Egg"
  recipe:
    - BLAZE_ROD BLAZE_ROD BLAZE_ROD
    - BLAZE_ROD EGG BLAZE_ROD
    - BLAZE_ROD BLAZE_ROD BLAZE_ROD
  material: BLAZE_SPAWN_EGG

CreeperSpawnEgg:
  name: "Creeper Spawn Egg"
  recipe:
    - GUNPOWDER GUNPOWDER GUNPOWDER
    - GUNPOWDER EGG GUNPOWDER
    - GUNPOWDER GUNPOWDER GUNPOWDER
  material: CREEPER_SPAWN_EGG

DrownedSpawnEgg:
  name: "Drowned Spawn Egg"
  recipe:
    - TRIDENT TRIDENT TRIDENT
    - TRIDENT EGG TRIDENT
    - TRIDENT TRIDENT TRIDENT
  material: DROWNED_SPAWN_EGG

EndermanSpawnEgg:
  name: "Enderman Spawn Egg"
  recipe:
    - ENDER_PEARL ENDER_PEARL ENDER_PEARL
    - ENDER_PEARL EGG ENDER_PEARL
    - ENDER_PEARL ENDER_PEARL ENDER_PEARL
  material: ENDERMAN_SPAWN_EGG

GhastSpawnEgg:
  name: "Ghast Spawn Egg"
  recipe:
    - GHAST_TEAR GHAST_TEAR GHAST_TEAR
    - GHAST_TEAR EGG GHAST_TEAR
    - GHAST_TEAR GHAST_TEAR GHAST_TEAR
  material: GHAST_SPAWN_EGG

MagmaCubeSpawnEgg:
  name: "Magma Cube Spawn Egg"
  recipe:
    - MAGMA_CREAM MAGMA_CREAM MAGMA_CREAM
    - MAGMA_CREAM EGG MAGMA_CREAM
    - MAGMA_CREAM MAGMA_CREAM MAGMA_CREAM
  material: MAGMA_CUBE_SPAWN_EGG

PandaSpawnEgg:
  name: "Panda Spawn Egg"
  recipe:
    - BAMBOO BAMBOO BAMBOO
    - BAMBOO EGG BAMBOO
    - BAMBOO BAMBOO BAMBOO
  material: PANDA_SPAWN_EGG

PigSpawnEgg:
  name: "Pig Spawn Egg"
  recipe:
    - PORKCHOP PORKCHOP PORKCHOP
    - PORKCHOP EGG PORKCHOP
    - PORKCHOP PORKCHOP PORKCHOP
  material: PIG_SPAWN_EGG

RavagerSpawnEgg:
  name: "Ravager Spawn Egg"
  recipe:
    - SADDLE SADDLE SADDLE
    - SADDLE EGG SADDLE
    - SADDLE SADDLE SADDLE
  material: RAVAGER_SPAWN_EGG

ShulkerSpawnEgg:
  name: "Shulker Spawn Egg"
  recipe:
    - SHULKER_SHELL SHULKER_SHELL SHULKER_SHELL
    - SHULKER_SHELL EGG SHULKER_SHELL
    - SHULKER_SHELL SHULKER_SHELL SHULKER_SHELL
  material: SHULKER_SPAWN_EGG

SkeletonSpawnEgg:
  name: "Skeleton Spawn Egg"
  recipe:
    - BONE BONE BONE
    - BONE EGG BONE
    - BONE BONE BONE
  material: SKELETON_SPAWN_EGG

SlimeSpawnEgg:
  name: "Slime Spawn Egg"
  recipe:
    - SLIME_BALL SLIME_BALL SLIME_BALL
    - SLIME_BALL EGG SLIME_BALL
    - SLIME_BALL SLIME_BALL SLIME_BALL
  material: SLIME_SPAWN_EGG

SpiderSpawnEgg:
  name: "Spider Spawn Egg"
  recipe:
    - SPIDER_EYE SPIDER_EYE SPIDER_EYE
    - SPIDER_EYE EGG SPIDER_EYE
    - SPIDER_EYE SPIDER_EYE SPIDER_EYE
  material: SPIDER_SPAWN_EGG

WitherSkeletonSpawnEgg:
  name: "Wither Skeleton Spawn Egg"
  recipe:
    - WITHER_SKELETON_SKULL WITHER_SKELETON_SKULL WITHER_SKELETON_SKULL
    - WITHER_SKELETON_SKULL EGG WITHER_SKELETON_SKULL
    - WITHER_SKELETON_SKULL WITHER_SKELETON_SKULL WITHER_SKELETON_SKULL
  material: WITHER_SKELETON_SPAWN_EGG

ZombieSpawnEgg:
  name: "Zombie Spawn Egg"
  recipe:
    - ROTTEN_FLESH ROTTEN_FLESH ROTTEN_FLESH
    - ROTTEN_FLESH EGG ROTTEN_FLESH
    - ROTTEN_FLESH ROTTEN_FLESH ROTTEN_FLESH
  material: ZOMBIE_SPAWN_EGG

Sponge:
  name: "Sponge"
  recipe:
    - DIRT DIRT DIRT
    - DIRT WATER_BUCKET DIRT
    - DIRT DIRT DIRT
  material: SPONGE