#
# ==== General info ====
#
# * If a field have default value then the definition may be skipped.
#
# * You can add your own recipes in this file but don't forget to
# add they into 'enabled-recipes' list
#
# * After editing of this file you need to check server logs to be
# sure that no errors was appeared.
#

#
# Show debug info. Possible values: true | false (default = false)
#
# This option can affect the performance.
#
debug: false


# List of keys of enabled recipes
# <recipe-key1>
# ...
# <recipe-keyN>
enabled-recipes:
  - ArmadilloSpawnEgg
  - BeeSpawnEgg
  - BlazeSpawnEgg
  - BreezeSpawnEgg
  - CodSpawnEgg
  - CowSpawnEgg
  - CreeperSpawnEgg
  - DrownedSpawnEgg
  - ElderGuardianSpawnEgg
  - EndermanSpawnEgg
  - EvokerSpawnEgg
  - GhastSpawnEgg
  - GlowSquidSpawnEgg
  - MagmaCubeSpawnEgg
  - PandaSpawnEgg
  - ParrotSpawnEgg
  - PhantomSpawnEgg
  - PigSpawnEgg
  - PillagerSpawnEgg
  - PufferfishSpawnEgg
  - RabbitSpawnEgg
  - RavagerSpawnEgg
  - SalmonSpawnEgg
  - SheepSpawnEgg
  - ShulkerSpawnEgg
  - SkeletonSpawnEgg
  - SlimeSpawnEgg
  - SpiderSpawnEgg
  - SquidSpawnEgg
  - TropicalFishSpawnEgg
  - TurtleSpawnEgg
  - VindicatorSpawnEgg
  - WardenSpawnEgg
  - WitherSkeletonSpawnEgg
  - ZombieSpawnEgg

#
# ==== Recipes definition ====
# Example:
#
# <recipe-key>:
#   name: <String>
#   description: (default = empty)
#     - <String1>
#     ...
#     - <StringN>
#   recipe: (see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html)
#     - <BlockId11> <BlockId12> <BlockId13>
#     - <BlockId21> <BlockId22> <BlockId23>
#     - <BlockId31> <BlockId32> <BlockId33>
#   item: ### target item in recipe result
#   amount: <1..64> ### target amount of items in recipe result (default = 1)
#

ArmadilloSpawnEgg:
  recipe:
    - ARMADILLO_SCUTE ARMADILLO_SCUTE ARMADILLO_SCUTE
    - ARMADILLO_SCUTE CLOCK ARMADILLO_SCUTE
    - ARMADILLO_SCUTE ARMADILLO_SCUTE ARMADILLO_SCUTE
  material: ARMADILLO_SPAWN_EGG

BeeSpawnEgg:
  recipe:
    - HONEY_BOTTLE HONEY_BOTTLE HONEY_BOTTLE
    - HONEY_BOTTLE CLOCK HONEY_BOTTLE
    - HONEY_BOTTLE HONEY_BOTTLE HONEY_BOTTLE
  material: BEE_SPAWN_EGG

BlazeSpawnEgg:
  recipe:
    - BLAZE_ROD BLAZE_ROD BLAZE_ROD
    - BLAZE_ROD CLOCK BLAZE_ROD
    - BLAZE_ROD BLAZE_ROD BLAZE_ROD
  material: BLAZE_SPAWN_EGG

BreezeSpawnEgg:
  recipe:
    - BREEZE_ROD BREEZE_ROD BREEZE_ROD
    - BREEZE_ROD CLOCK BREEZE_ROD
    - BREEZE_ROD BREEZE_ROD BREEZE_ROD
  material: BREEZE_SPAWN_EGG

CodSpawnEgg:
  recipe:
    - COD COD COD
    - COD CLOCK COD
    - COD COD COD
  material: COD_SPAWN_EGG

CowSpawnEgg:
  recipe:
    - BEEF BEEF BEEF
    - BEEF CLOCK BEEF
    - BEEF BEEF BEEF
  material: COW_SPAWN_EGG

CreeperSpawnEgg:
  recipe:
    - GUNPOWDER GUNPOWDER GUNPOWDER
    - GUNPOWDER CLOCK GUNPOWDER
    - GUNPOWDER GUNPOWDER GUNPOWDER
  material: CREEPER_SPAWN_EGG

DrownedSpawnEgg:
  recipe:
    - TRIDENT TRIDENT TRIDENT
    - TRIDENT CLOCK TRIDENT
    - TRIDENT TRIDENT TRIDENT
  material: DROWNED_SPAWN_EGG

ElderGuardianSpawnEgg:
  recipe:
    - WET_SPONGE WET_SPONGE WET_SPONGE
    - WET_SPONGE CLOCK WET_SPONGE
    - WET_SPONGE WET_SPONGE WET_SPONGE
  material: ELDER_GUARDIAN_SPAWN_EGG

EndermanSpawnEgg:
  recipe:
    - ENDER_PEARL ENDER_PEARL ENDER_PEARL
    - ENDER_PEARL CLOCK ENDER_PEARL
    - ENDER_PEARL ENDER_PEARL ENDER_PEARL
  material: ENDERMAN_SPAWN_EGG

EvokerSpawnEgg:
  recipe:
    - TOTEM_OF_UNDYING TOTEM_OF_UNDYING TOTEM_OF_UNDYING
    - TOTEM_OF_UNDYING CLOCK TOTEM_OF_UNDYING
    - TOTEM_OF_UNDYING TOTEM_OF_UNDYING TOTEM_OF_UNDYING
  material: EVOKER_SPAWN_EGG

GhastSpawnEgg:
  recipe:
    - GHAST_TEAR GHAST_TEAR GHAST_TEAR
    - GHAST_TEAR CLOCK GHAST_TEAR
    - GHAST_TEAR GHAST_TEAR GHAST_TEAR
  material: GHAST_SPAWN_EGG

GlowSquidSpawnEgg:
  recipe:
    - GLOW_INK_SAC GLOW_INK_SAC GLOW_INK_SAC
    - GLOW_INK_SAC CLOCK GLOW_INK_SAC
    - GLOW_INK_SAC GLOW_INK_SAC GLOW_INK_SAC
  material: GLOW_SQUID_SPAWN_EGG

MagmaCubeSpawnEgg:
  recipe:
    - MAGMA_CREAM MAGMA_CREAM MAGMA_CREAM
    - MAGMA_CREAM CLOCK MAGMA_CREAM
    - MAGMA_CREAM MAGMA_CREAM MAGMA_CREAM
  material: MAGMA_CUBE_SPAWN_EGG

PandaSpawnEgg:
  recipe:
    - BAMBOO BAMBOO BAMBOO
    - BAMBOO CLOCK BAMBOO
    - BAMBOO BAMBOO BAMBOO
  material: PANDA_SPAWN_EGG

ParrotSpawnEgg:
  recipe:
    - FEATHER FEATHER FEATHER
    - FEATHER CLOCK FEATHER
    - FEATHER FEATHER FEATHER
  material: PARROT_SPAWN_EGG

PhantomSpawnEgg:
  recipe:
    - PHANTOM_MEMBRANE PHANTOM_MEMBRANE PHANTOM_MEMBRANE
    - PHANTOM_MEMBRANE CLOCK PHANTOM_MEMBRANE
    - PHANTOM_MEMBRANE PHANTOM_MEMBRANE PHANTOM_MEMBRANE
  material: PHANTOM_SPAWN_EGG

PigSpawnEgg:
  recipe:
    - PORKCHOP PORKCHOP PORKCHOP
    - PORKCHOP CLOCK PORKCHOP
    - PORKCHOP PORKCHOP PORKCHOP
  material: PIG_SPAWN_EGG

PillagerSpawnEgg:
  recipe:
    - CROSSBOW CROSSBOW CROSSBOW
    - CROSSBOW CLOCK CROSSBOW
    - CROSSBOW CROSSBOW CROSSBOW
  material: PILLAGER_SPAWN_EGG

PufferfishSpawnEgg:
  recipe:
    - PUFFERFISH PUFFERFISH PUFFERFISH
    - PUFFERFISH CLOCK PUFFERFISH
    - PUFFERFISH PUFFERFISH PUFFERFISH
  material: PUFFERFISH_SPAWN_EGG

RabbitSpawnEgg:
  recipe:
    - RABBIT RABBIT RABBIT
    - RABBIT CLOCK RABBIT
    - RABBIT RABBIT RABBIT
  material: RABBIT_SPAWN_EGG

RavagerSpawnEgg:
  recipe:
    - SADDLE SADDLE SADDLE
    - SADDLE CLOCK SADDLE
    - SADDLE SADDLE SADDLE
  material: RAVAGER_SPAWN_EGG

SalmonSpawnEgg:
  recipe:
    - SALMON SALMON SALMON
    - SALMON CLOCK SALMON
    - SALMON SALMON SALMON
  material: SALMON_SPAWN_EGG

SheepSpawnEgg:
  recipe:
    - MUTTON MUTTON MUTTON
    - MUTTON CLOCK MUTTON
    - MUTTON MUTTON MUTTON
  material: SHEEP_SPAWN_EGG

ShulkerSpawnEgg:
  recipe:
    - SHULKER_SHELL SHULKER_SHELL SHULKER_SHELL
    - SHULKER_SHELL CLOCK SHULKER_SHELL
    - SHULKER_SHELL SHULKER_SHELL SHULKER_SHELL
  material: SHULKER_SPAWN_EGG

SkeletonSpawnEgg:
  recipe:
    - BONE BONE BONE
    - BONE CLOCK BONE
    - BONE BONE BONE
  material: SKELETON_SPAWN_EGG

SlimeSpawnEgg:
  recipe:
    - SLIME_BALL SLIME_BALL SLIME_BALL
    - SLIME_BALL CLOCK SLIME_BALL
    - SLIME_BALL SLIME_BALL SLIME_BALL
  material: SLIME_SPAWN_EGG

SpiderSpawnEgg:
  recipe:
    - SPIDER_EYE SPIDER_EYE SPIDER_EYE
    - SPIDER_EYE CLOCK SPIDER_EYE
    - SPIDER_EYE SPIDER_EYE SPIDER_EYE
  material: SPIDER_SPAWN_EGG

SquidSpawnEgg:
  recipe:
    - INK_SAC INK_SAC INK_SAC
    - INK_SAC CLOCK INK_SAC
    - INK_SAC INK_SAC INK_SAC
  material: SQUID_SPAWN_EGG

TropicalFishSpawnEgg:
  recipe:
    - TROPICAL_FISH TROPICAL_FISH TROPICAL_FISH
    - TROPICAL_FISH CLOCK TROPICAL_FISH
    - TROPICAL_FISH TROPICAL_FISH TROPICAL_FISH
  material: TROPICAL_FISH_SPAWN_EGG

TurtleSpawnEgg:
  recipe:
    - TURTLE_SCUTE TURTLE_SCUTE TURTLE_SCUTE
    - TURTLE_SCUTE CLOCK TURTLE_SCUTE
    - TURTLE_SCUTE TURTLE_SCUTE TURTLE_SCUTE
  material: TURTLE_SPAWN_EGG

VindicatorSpawnEgg:
  recipe:
    - IRON_AXE IRON_AXE IRON_AXE
    - IRON_AXE CLOCK IRON_AXE
    - IRON_AXE IRON_AXE IRON_AXE
  material: VINDICATOR_SPAWN_EGG

WardenSpawnEgg:
  recipe:
    - SCULK_CATALYST SCULK_CATALYST SCULK_CATALYST
    - SCULK_CATALYST CLOCK SCULK_CATALYST
    - SCULK_CATALYST SCULK_CATALYST SCULK_CATALYST
  material: WARDEN_SPAWN_EGG

WitherSkeletonSpawnEgg:
  recipe:
    - WITHER_SKELETON_SKULL WITHER_SKELETON_SKULL WITHER_SKELETON_SKULL
    - WITHER_SKELETON_SKULL CLOCK WITHER_SKELETON_SKULL
    - WITHER_SKELETON_SKULL WITHER_SKELETON_SKULL WITHER_SKELETON_SKULL
  material: WITHER_SKELETON_SPAWN_EGG

ZombieSpawnEgg:
  recipe:
    - ROTTEN_FLESH ROTTEN_FLESH ROTTEN_FLESH
    - ROTTEN_FLESH CLOCK ROTTEN_FLESH
    - ROTTEN_FLESH ROTTEN_FLESH ROTTEN_FLESH
  material: ZOMBIE_SPAWN_EGG
