#
# ==== General info ====
#
# * If a field have default value then the definition may be skipped.
#
# * You can add your own recipes in this file but don't forget to
# add they into 'enabled-recipes' list
#
# * After editing of this file you need to check server logs to be
# sure that no errors was appeared.
#

#
# Show debug info. Possible values: true | false (default = false)
#
# This option can affect the performance.
#
debug: false


# List of keys of enabled recipes
# <recipe-key1>
# ...
# <recipe-keyN>
enabled-recipes:
  - PigSpawner

  - BlazeSpawnEgg
  - CodSpawnEgg
  - CowSpawnEgg
  - CreeperSpawnEgg
  - DrownedSpawnEgg
  - EndermanSpawnEgg
  - EvokerSpawnEgg
  - GhastSpawnEgg
  - GlowSquidSpawnEgg
  - MagmaCubeSpawnEgg
  - PandaSpawnEgg
  - PhantomSpawnEgg
  - PigSpawnEgg
  - PillagerSpawnEgg
  - PufferfishSpawnEgg
  - RabbitSpawnEgg
  - RavagerSpawnEgg
  - SalmonSpawnEgg
  - SheepSpawnEgg
  - ShulkerSpawnEgg
  - SkeletonSpawnEgg
  - SlimeSpawnEgg
  - SpiderSpawnEgg
  - SquidSpawnEgg
  - TropicalFishSpawnEgg
  - TurtleSpawnEgg
  - VindicatorSpawnEgg
  - WardenSpawnEgg
  - WitherSkeletonSpawnEgg
  - ZombieSpawnEgg

  - Cobblestone
  - Sponge
  - Stick
  - String

#
# ==== Recipes definition ====
# Example:
#
# <recipe-key>:
#   name: <String>
#   description: (default = empty)
#     - <String1>
#     ...
#     - <StringN>
#   recipe: (see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html)
#     - <BlockId11> <BlockId12> <BlockId13>
#     - <BlockId21> <BlockId22> <BlockId23>
#     - <BlockId31> <BlockId32> <BlockId33>
#   item: ### target item in recipe result
#   amount: <1..64> ### target amount of items in recipe result (default = 1)
#

PigSpawner:
  name: "Pig Spawner"
  description:
    - "The pig can be changed"
    - "by using a mob spawn egg"
    - "on the block."
  recipe:
    - IRON_BLOCK PORKCHOP IRON_BLOCK
    - PORKCHOP CLOCK PORKCHOP
    - IRON_BLOCK PORKCHOP IRON_BLOCK
  material: SPAWNER

BlazeSpawnEgg:
  name: "Blaze Spawn Egg"
  recipe:
    - BLAZE_ROD BLAZE_ROD BLAZE_ROD
    - BLAZE_ROD EGG BLAZE_ROD
    - BLAZE_ROD BLAZE_ROD BLAZE_ROD
  material: BLAZE_SPAWN_EGG

CodSpawnEgg:
  name: "Cod Spawn Egg"
  recipe:
    - COD COD COD
    - COD EGG COD
    - COD COD COD
  material: COD_SPAWN_EGG

CowSpawnEgg:
  name: "Cow Spawn Egg"
  recipe:
    - BEEF BEEF BEEF
    - BEEF EGG BEEF
    - BEEF BEEF BEEF
  material: COW_SPAWN_EGG

CreeperSpawnEgg:
  name: "Creeper Spawn Egg"
  recipe:
    - GUNPOWDER GUNPOWDER GUNPOWDER
    - GUNPOWDER EGG GUNPOWDER
    - GUNPOWDER GUNPOWDER GUNPOWDER
  material: CREEPER_SPAWN_EGG

DrownedSpawnEgg:
  name: "Drowned Spawn Egg"
  recipe:
    - TRIDENT TRIDENT TRIDENT
    - TRIDENT EGG TRIDENT
    - TRIDENT TRIDENT TRIDENT
  material: DROWNED_SPAWN_EGG

EndermanSpawnEgg:
  name: "Enderman Spawn Egg"
  recipe:
    - ENDER_PEARL ENDER_PEARL ENDER_PEARL
    - ENDER_PEARL EGG ENDER_PEARL
    - ENDER_PEARL ENDER_PEARL ENDER_PEARL
  material: ENDERMAN_SPAWN_EGG

EvokerSpawnEgg:
  name: "Evoker Spawn Egg"
  recipe:
    - TOTEM_OF_UNDYING TOTEM_OF_UNDYING TOTEM_OF_UNDYING
    - TOTEM_OF_UNDYING EGG TOTEM_OF_UNDYING
    - TOTEM_OF_UNDYING TOTEM_OF_UNDYING TOTEM_OF_UNDYING
  material: EVOKER_SPAWN_EGG

GhastSpawnEgg:
  name: "Ghast Spawn Egg"
  recipe:
    - GHAST_TEAR GHAST_TEAR GHAST_TEAR
    - GHAST_TEAR EGG GHAST_TEAR
    - GHAST_TEAR GHAST_TEAR GHAST_TEAR
  material: GHAST_SPAWN_EGG

GlowSquidSpawnEgg:
  name: "Glow Squid Spawn Egg"
  recipe:
    - GLOW_INK_SAC GLOW_INK_SAC GLOW_INK_SAC
    - GLOW_INK_SAC EGG GLOW_INK_SAC
    - GLOW_INK_SAC GLOW_INK_SAC GLOW_INK_SAC
  material: GLOW_SQUID_SPAWN_EGG

MagmaCubeSpawnEgg:
  name: "Magma Cube Spawn Egg"
  recipe:
    - MAGMA_CREAM MAGMA_CREAM MAGMA_CREAM
    - MAGMA_CREAM EGG MAGMA_CREAM
    - MAGMA_CREAM MAGMA_CREAM MAGMA_CREAM
  material: MAGMA_CUBE_SPAWN_EGG

PandaSpawnEgg:
  name: "Panda Spawn Egg"
  recipe:
    - BAMBOO BAMBOO BAMBOO
    - BAMBOO EGG BAMBOO
    - BAMBOO BAMBOO BAMBOO
  material: PANDA_SPAWN_EGG

PhantomSpawnEgg:
  name: "Phantom Spawn Egg"
  recipe:
    - PHANTOM_MEMBRANE PHANTOM_MEMBRANE PHANTOM_MEMBRANE
    - PHANTOM_MEMBRANE EGG PHANTOM_MEMBRANE
    - PHANTOM_MEMBRANE PHANTOM_MEMBRANE PHANTOM_MEMBRANE
  material: PHANTOM_SPAWN_EGG

PigSpawnEgg:
  name: "Pig Spawn Egg"
  recipe:
    - PORKCHOP PORKCHOP PORKCHOP
    - PORKCHOP EGG PORKCHOP
    - PORKCHOP PORKCHOP PORKCHOP
  material: PIG_SPAWN_EGG

PillagerSpawnEgg:
  name: "Pillager Spawn Egg"
  recipe:
    - CROSSBOW CROSSBOW CROSSBOW
    - CROSSBOW EGG CROSSBOW
    - CROSSBOW CROSSBOW CROSSBOW
  material: PILLAGER_SPAWN_EGG

PufferfishSpawnEgg:
  name: "Pufferfish Spawn Egg"
  recipe:
    - PUFFERFISH PUFFERFISH PUFFERFISH
    - PUFFERFISH EGG PUFFERFISH
    - PUFFERFISH PUFFERFISH PUFFERFISH
  material: PUFFERFISH_SPAWN_EGG

RabbitSpawnEgg:
  name: "Rabbit Spawn Egg"
  recipe:
    - RABBIT RABBIT RABBIT
    - RABBIT EGG RABBIT
    - RABBIT RABBIT RABBIT
  material: RABBIT_SPAWN_EGG

RavagerSpawnEgg:
  name: "Ravager Spawn Egg"
  recipe:
    - SADDLE SADDLE SADDLE
    - SADDLE EGG SADDLE
    - SADDLE SADDLE SADDLE
  material: RAVAGER_SPAWN_EGG

SalmonSpawnEgg:
  name: "Salmon Spawn Egg"
  recipe:
    - SALMON SALMON SALMON
    - SALMON EGG SALMON
    - SALMON SALMON SALMON
  material: SALMON_SPAWN_EGG

SheepSpawnEgg:
  name: "Sheep Spawn Egg"
  recipe:
    - MUTTON MUTTON MUTTON
    - MUTTON EGG MUTTON
    - MUTTON MUTTON MUTTON
  material: SHEEP_SPAWN_EGG

ShulkerSpawnEgg:
  name: "Shulker Spawn Egg"
  recipe:
    - SHULKER_SHELL SHULKER_SHELL SHULKER_SHELL
    - SHULKER_SHELL EGG SHULKER_SHELL
    - SHULKER_SHELL SHULKER_SHELL SHULKER_SHELL
  material: SHULKER_SPAWN_EGG

SkeletonSpawnEgg:
  name: "Skeleton Spawn Egg"
  recipe:
    - BONE BONE BONE
    - BONE EGG BONE
    - BONE BONE BONE
  material: SKELETON_SPAWN_EGG

SlimeSpawnEgg:
  name: "Slime Spawn Egg"
  recipe:
    - SLIME_BALL SLIME_BALL SLIME_BALL
    - SLIME_BALL EGG SLIME_BALL
    - SLIME_BALL SLIME_BALL SLIME_BALL
  material: SLIME_SPAWN_EGG

SpiderSpawnEgg:
  name: "Spider Spawn Egg"
  recipe:
    - SPIDER_EYE SPIDER_EYE SPIDER_EYE
    - SPIDER_EYE EGG SPIDER_EYE
    - SPIDER_EYE SPIDER_EYE SPIDER_EYE
  material: SPIDER_SPAWN_EGG

SquidSpawnEgg:
  name: "Squid Spawn Egg"
  recipe:
    - INK_SAC INK_SAC INK_SAC
    - INK_SAC EGG INK_SAC
    - INK_SAC INK_SAC INK_SAC
  material: SQUID_SPAWN_EGG

TropicalFishSpawnEgg:
  name: "Tropical Fish Spawn Egg"
  recipe:
    - TROPICAL_FISH TROPICAL_FISH TROPICAL_FISH
    - TROPICAL_FISH EGG TROPICAL_FISH
    - TROPICAL_FISH TROPICAL_FISH TROPICAL_FISH
  material: TROPICAL_FISH_SPAWN_EGG

TurtleSpawnEgg:
  name: "Turtle Spawn Egg"
  recipe:
    - SCUTE SCUTE SCUTE
    - SCUTE EGG SCUTE
    - SCUTE SCUTE SCUTE
  material: TURTLE_SPAWN_EGG

VindicatorSpawnEgg:
  name: "Vindicator Spawn Egg"
  recipe:
    - IRON_AXE IRON_AXE IRON_AXE
    - IRON_AXE EGG IRON_AXE
    - IRON_AXE IRON_AXE IRON_AXE
  material: VINDICATOR_SPAWN_EGG

WitherSkeletonSpawnEgg:
  name: "Wither Skeleton Spawn Egg"
  recipe:
    - WITHER_SKELETON_SKULL WITHER_SKELETON_SKULL WITHER_SKELETON_SKULL
    - WITHER_SKELETON_SKULL EGG WITHER_SKELETON_SKULL
    - WITHER_SKELETON_SKULL WITHER_SKELETON_SKULL WITHER_SKELETON_SKULL
  material: WITHER_SKELETON_SPAWN_EGG

WardenSpawnEgg:
  name: "Warden Spawn Egg"
  recipe:
    - SCULK_CATALYST SCULK_CATALYST SCULK_CATALYST
    - SCULK_CATALYST EGG SCULK_CATALYST
    - SCULK_CATALYST SCULK_CATALYST SCULK_CATALYST
  material: WARDEN_SPAWN_EGG

ZombieSpawnEgg:
  name: "Zombie Spawn Egg"
  recipe:
    - ROTTEN_FLESH ROTTEN_FLESH ROTTEN_FLESH
    - ROTTEN_FLESH EGG ROTTEN_FLESH
    - ROTTEN_FLESH ROTTEN_FLESH ROTTEN_FLESH
  material: ZOMBIE_SPAWN_EGG

Cobblestone:
  name: "Cobblestone"
  recipe:
    - BONE BONE BONE
    - BONE BONE BONE
    - BONE BONE BONE
  material: COBBLESTONE

Sponge:
  name: "Sponge"
  recipe:
    - SAND SAND SAND
    - SAND NETHER_STAR SAND
    - SAND SAND SAND
  material: SPONGE
  amount: 8

Stick:
  name: "Stick"
  recipe:
    - ARROW ARROW ARROW
    - ARROW ARROW ARROW
    - ARROW ARROW ARROW
  material: STICK

String:
  name: "String"
  recipe:
    - BOW BOW BOW
    - BOW BOW BOW
    - BOW BOW BOW
  material: STRING
  amount: 7