name: CustomRecipes
main: com.gmail.uprial.customrecipes.CustomRecipes
version: 0.2.0
api-version: 1.14
commands:
   customrecipes:
      description: Reload CustomRecipes config
      usage: /customrecipes help
      permission:
      permission-message:
permissions:
  customrecipes.reload:
        description: Gives access to CustomRecipes 'reload' command
        default: op
